#!/usr/bin/env bash
# this script is displaying "Best School" 20 times
count=1
while [ $counter -le 20 ]
do
	case $count in
4)
	echo "4 bad luck from China"
		;;
9)
	echo "9 bad luck from Japan"
		;;
17)
	echo "17 bad luck from Italy"
		;;

*)
	echo "$count"
		;;
esac
count=$((count+1))
done
