#!/usr/bin/env bash
#This is how you manage a file

DINO=/var/run/my_process.pid

case "$1" in
    start)
        bash manage_my_process &
        echo $! > $DINO
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat $DINO)"
        rm $DINO
        echo "manage_my_process stopped"
        ;;
restart)
        kill "$(cat $DINO)"
        rm $DINO
        bash manage_my_process &
        echo $! > $DINO
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
