#!/usr/bin/env bash
# script that displays to infinity and beyond and i am invincible.

trap "echo i am invincible!!!" SIGTERM
x=1
while [ "$x" -gt 0 ]
do
	echo "to infinity and beyond"
	x=$((x+1))
	sleep 2
done
